---
- name: Install multi-tier-app postgres backend
  hosts: app_backends
  gather_facts: true
  become: true
  tags:
    - app_backends

  tasks:

    - name: Install Postgresql
      ansible.builtin.include_role:
        name: geerlingguy.postgresql

- name: Deploy, configure, and populate flask application
  hosts: app_frontends
  become: true
  gather_facts: true
  tags:
    - app_frontends

  roles:

    - flask

# - name: Smoketest application
#   hosts: app_frontend
#   gather_facts: true
#   become: false
#   tags:
#     - smoketest
#
#   roles:
#
#     - smoketest

...    
