---
- name: Add database IP address to app servers /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    regexp: '.*app_frontend$'
    line: "{{ groups.app_backends[0] }} app-backend"
#    line: "{{ hostvars['appdb1']['ansible_default_ipv4']['address'] }} appdb1"
    state: present

- name: Create flask user
  ansible.builtin.user:
    name: "{{ flask_user }}"
    state: present  

- name: Install flask packages including postgres pre-reqs
  ansible.builtin.dnf:
    name: "{{ __package }}"
    state: present
    disable_gpg_check: true
  loop: 
    - "{{ postgres_rhel9_repo }}"
    - "{{ app_yum_packages }}"        
    - "{{ postgres_library }}"
  loop_control:
    loop_var: __package

- name: "Install flask repo {{ flask_repo }}"
  ansible.builtin.git:
    repo: "{{ flask_repo }}"
    dest: "{{ flask_home }}/{{ flask_app_name }}"
    version: rh1-2023-aap2-containerized
    #    version: next-gen
    update: yes 
    force: yes
  ignore_errors: true
  tags:
    - git

- name: "Change flash repo owner to {{ flask_user }} recursively"      
  ansible.builtin.file: 
    dest: "{{ flask_home }}/{{ flask_app_name }}"
    owner: "{{ flask_user }}"

- name: Python setup
  block:

    - name: Setup pre-requisite pip3 packages
      ansible.builtin.pip:
        name: "{{ pip_dependencies }}"
        state: latest
        executable: /usr/bin/pip3.9

    # - name: "Create virtualenv {{ virtualenv_name }} for Flask"
    #   ansible.builtin.pip:
    #     requirements: "{{ flask_home }}/{{ flask_app_name }}/requirements.txt"
    #     virtualenv: "{{ virtualenv_home }}/{{ flask_app_name }}"
    #     virtualenv_site_packages: no
    #     virtualenv_command: /usr/local/bin/virtualenv
      
- name: Initialize flask app database resources
  ansible.builtin.command: "/usr/bin/python3 {{ flask_home }}/{{ flask_app_name }}/config.py"
  run_once: true

- name: "Generate {{ flask_app_name }} startup script"    
  ansible.builtin.template:
    src: launch_resource_hub.j2
    dest: /usr/local/bin/launch_resource_hub   
    mode: '0555'

- name: template systemd service config
  ansible.builtin.template:
    src: flask_service.j2
    dest: /etc/systemd/system/{{ flask_app_name }}.service
    mode: '0755'

- name: start systemd app service
  ansible.builtin.systemd: 
    name: "{{ flask_app_name }}.service"
    state: restarted 
    enabled: yes

...
