---
- name: End to end smoke tests
  hosts: app_servers:database_servers
  gather_facts: true
  become: true
  tags:
    - smoketest

  tasks:

    - name: Validate database IP
      ansible.builtin.debug:
        msg:
          - "IP is {{ hostvars['database01']['ansible_default_ipv4']['address'] }}"
          - "First App server  {{ groups.app_servers[0] }}"
        verbosity: 2

    - name: Smoketest Postgres database
      community.postgresql.postgresql_ping:
        db: flask_db
        # login_host: "{{ hostvars['database01'].ansible_default_ipv4.address }}"
        login_host: "{{ hostvars[groups.database_servers[0]].ansible_default_ipv4.address }}"
        login_user: flask
        login_password: redhat
        ssl_mode: disable
      delegate_to: "{{ groups.app_servers[0] }}"
      run_once: true
      tags:
        - smoketest

- name: End to end smoke tests
  hosts: app_servers
  become: false
  gather_facts: false
  tags:
    - smoketest
  tasks:

    - name: Check webserver for correct response
      ansible.builtin.uri:
        url: "http://{{ hostvars[groups.app_servers[0]].ansible_default_ipv4.address }}/ping"
        return_content: true
      until: '"alive" in r_result.content'
      retries: 10
      delay: 1
      register: r_result
      delegate_to: localhost

...
