---
postgres_rhel9_repo: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm"

postgres_packages:
  #  - postgresql13
  - postgresql13-server
  - postgresql13-contrib
  - postgresql13-libs
  - python3-psycopg2
  # postgres_library: python-psycopg2
postgres_13_data_dir: /var/lib/pgsql/13/data
postgres_13_bin_path: /usr/pgsql-13/bin
postgres_service: postgresql-13.service
postgres_port: 5432
postgres_user: postgres

flask_app_name: resource_hub
flask_user: flask
flask_home: /opt/
flask_repo: https://github.com/redhat-gpe/multi-tier-app.git
flask_scm_ref: main
flask_app_lauch_script: /usr/local/bin/launch_resource_hub
virtualenv_name: "venv-{{ flask_app_name }}"
virtualenv_home: /opt/virtual_envs
virtualenv_python: /usr/bin/python3
pip_dependencies: []
# - virtualenv
# - pip
# - psycopg2-binary
...
